Feature/dumper
st3n/project-TehnoCat pull request #1
Opened 2023-12-20 19:47 UTC by staskut

2023-12-20 21:33 UTC, st3n approved these changes

2023-12-21 13:35 UTC, gregorytereshko commented on phone_book.py
> +        contacts.dump()
Я бы дампы и лоады делал в main() перед и после выполнения каждой команды. А то если миллион команд на изменение будет - задолбемся везде добавлять
(да и не обязанность это метода change делать дамп)

2023-12-21 14:27 UTC, st3n requested changes

2023-12-21 14:27 UTC, st3n commented on phone_book.py
> +        contacts.dump()
ти пропонуєш робити дамп при виході із мейна а лоад при запуску програми, вірно? в цілому це ок, менше операцій з файловою системою, погоджуюсь. Тільки треба акарутно з екскпшенами

2023-12-21 14:31 UTC, gregorytereshko commented on phone_book.py
> +        contacts.dump()
Не
Дамп делать в цикле после КАЖДОЙ команды. Операций с ФС будет больше, но у нас требований к ресурсам никаких))
А лоад - да, 1 раз при запуске программы

2023-12-21 16:22 UTC, gregorytereshko commented on phone_book.py
> +        contacts.dump()
Да по факту не надо, просто быстрый и простой способ получить сохранение всегда актуальных данных
Если только в конце делать, то, действительно, в случае эксепшна ничего не сохранится. Тогда еще обработку эксепшна делать
Кроч, самый легкий и надежный вариант для того чтоб ничего не потерять

2023-12-21 17:16 UTC, staskut commented on phone_book.py
> +        contacts.dump()
перенес дампы в мейн после команд которые меняют книгу

2023-12-21 18:23 UTC, st3n approved these changes

2023-12-21 21:45 UTC, st3n approved these changes

2023-12-21 21:46 UTC, merged