Feature/packaging
st3n/project-TehnoCat pull request #2
Opened 2023-12-20 20:35 UTC by staskut

2023-12-20 21:29 UTC, st3n approved these changes

2023-12-20 21:52 UTC, st3n commented
I think we need to do next in terms of this PR:
1. create storage folder. Load and dump data there.
2. create src folder and move our modules there
3. all related to packing in separate dir

2023-12-21 06:20 UTC, staskut commented
> create storage folder. Load and dump data there.

 - agree, will do

As for two other points:

> create src folder and move our modules there 
> all related to packing in separate dir

- I was following suggestions we have in the course. Same here - https://betterscientificsoftware.github.io/python-for-hpc/tutorials/python-pypi-packaging/#creating-a-python-package

2023-12-21 13:36 UTC, gregorytereshko requested changes

2023-12-21 13:36 UTC, gregorytereshko commented on setup.py
> +setup(
добавь, пожалуйста, этот пакет в зависимости https://pypi.org/project/jaro-winkler/

2023-12-21 14:30 UTC, st3n commented
> > create storage folder. Load and dump data there.
> 
> * agree, will do
> 
> As for two other points:
> 
> > create src folder and move our modules there
> > all related to packing in separate dir
> 
> * I was following structure suggestions we have in the course. Same here - https://betterscientificsoftware.github.io/python-for-hpc/tutorials/python-pypi-packaging/#creating-a-python-package
>   So module files are in the similarly named subfolder, not src. and setup.py one level above.

pyexample  from this example is the our "src" folder.

2023-12-21 14:31 UTC, st3n commented
please provide a tittle adn description for PR

2023-12-21 16:31 UTC, gregorytereshko commented on setup.py
> +setup(
И это тоже, пожалуйста
`prompt_toolkit`

2023-12-21 18:21 UTC, st3n submitted a review, later dismissed

2023-12-21 21:52 UTC, gregorytereshko submitted a review, later dismissed

2023-12-22 10:47 UTC, st3n submitted a review, later dismissed

2023-12-22 11:13 UTC, st3n approved these changes

2023-12-22 11:13 UTC, merged